language: java
jdk: openjdk11

services:
  - docker

after_success:
  - export APP=aydarik/address-parser
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $APP:$TAG .
  - docker push $APP
